### ISSUE TITLE
Bug - Crash - Solved

### ISSUE THREAD

**Issue by SevenChords** [KidsDontPlay/PlayerStorage#15]
It happens way to often that the game crashes when you clear the crafting grid for me, happened 7 times today already, please find a way to fix this, since with a modpack that needs around 5 minutes to start, regular crashes are pretty bad.

**Comment by KidsDontPlay** [comment]
crash report file? or log file

**Comment by SevenChords** [comment]
it didn't save any crash report, the game just quit, the only thing i have is the log from the point where it crashed.
also if it helps in this particular instance it happened after i crafted something which resulted in me getting an advancement from vanilla minecraft, don't know if this was the case for the other times it happened.

[17:35:11] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.NoSuchElementException
	at it.unimi.dsi.fastutil.ints.IntArrayList$1.nextInt(IntArrayList.java:545) ~[IntArrayList$1.class:?]
	at it.unimi.dsi.fastutil.ints.AbstractIntCollection.addAll(AbstractIntCollection.java:127) ~[AbstractIntCollection.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.func_194097_a(RecipeItemHelper.java:212) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.<init>(RecipeItemHelper.java:121) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194118_a(RecipeItemHelper.java:79) ~[aef.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194116_a(RecipeItemHelper.java:74) ~[aef.class:?]
	at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(ShapelessRecipes.java:88) ~[akx.class:?]
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213) ~[aku.class:?]
	at mrriegel.playerstorage.gui.ContainerExI.func_75130_a(ContainerExI.java:223) ~[ContainerExI.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at mrriegel.playerstorage.Message2Server.handleMessage(Message2Server.java:57) ~[Message2Server.class:?]
	at mrriegel.limelib.network.AbstractMessage.lambda$onMessage$0(AbstractMessage.java:42) ~[AbstractMessage.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[17:35:13] [Server thread/INFO]: SevenChords has made the advancement [Spooky Scary Skeleton]
[17:35:13] [main/INFO]: [CHAT] SevenChords has made the advancement [Spooky Scary Skeleton]
[17:35:13] [main/INFO]: Loaded 717 advancements
[17:35:42] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.NoSuchElementException
	at it.unimi.dsi.fastutil.ints.IntArrayList$1.nextInt(IntArrayList.java:545) ~[IntArrayList$1.class:?]
	at it.unimi.dsi.fastutil.ints.AbstractIntCollection.addAll(AbstractIntCollection.java:127) ~[AbstractIntCollection.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.func_194097_a(RecipeItemHelper.java:212) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.<init>(RecipeItemHelper.java:121) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194118_a(RecipeItemHelper.java:79) ~[aef.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194116_a(RecipeItemHelper.java:74) ~[aef.class:?]
	at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(ShapelessRecipes.java:88) ~[akx.class:?]
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213) ~[aku.class:?]
	at mrriegel.playerstorage.gui.ContainerExI.func_75130_a(ContainerExI.java:223) ~[ContainerExI.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at mrriegel.playerstorage.Message2Server.handleMessage(Message2Server.java:57) ~[Message2Server.class:?]
	at mrriegel.limelib.network.AbstractMessage.lambda$onMessage$0(AbstractMessage.java:42) ~[AbstractMessage.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[17:35:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.NoSuchElementException
	at it.unimi.dsi.fastutil.ints.IntArrayList$1.nextInt(IntArrayList.java:545) ~[IntArrayList$1.class:?]
	at it.unimi.dsi.fastutil.ints.AbstractIntCollection.addAll(AbstractIntCollection.java:127) ~[AbstractIntCollection.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.func_194097_a(RecipeItemHelper.java:212) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.<init>(RecipeItemHelper.java:121) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194118_a(RecipeItemHelper.java:79) ~[aef.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194116_a(RecipeItemHelper.java:74) ~[aef.class:?]
	at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(ShapelessRecipes.java:88) ~[akx.class:?]
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213) ~[aku.class:?]
	at mrriegel.playerstorage.gui.ContainerExI.func_75130_a(ContainerExI.java:223) ~[ContainerExI.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:300) ~[afr.class:?]
	at mrriegel.playerstorage.gui.ContainerExI.func_184996_a(ContainerExI.java:194) ~[ContainerExI.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[17:37:11] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3351ms behind, skipping 67 tick(s)
[17:37:14] [Server thread/INFO]: Stopping server
[17:37:14] [Server thread/INFO]: Saving players
[17:37:14] [Server thread/INFO]: Saving worlds
[17:37:14] [Server thread/INFO]: Saving chunks for level 'survplaza1'/overworld
[17:37:14] [Server thread/INFO]: Saving chunks for level 'survplaza1'/the_nether
[17:37:14] [Server thread/INFO]: Saving chunks for level 'survplaza1'/the_end
[17:37:14] [Server thread/INFO]: Saving chunks for level 'survplaza1'/Deep Dark
[17:37:14] [Server thread/INFO]: Saving chunks for level 'survplaza1'/ExtraUtils2_Quarry_Dim
[17:37:23] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1770) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.util.NoSuchElementException
	at it.unimi.dsi.fastutil.ints.IntArrayList$1.nextInt(IntArrayList.java:545) ~[IntArrayList$1.class:?]
	at it.unimi.dsi.fastutil.ints.AbstractIntCollection.addAll(AbstractIntCollection.java:127) ~[AbstractIntCollection.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.func_194097_a(RecipeItemHelper.java:212) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper$RecipePicker.<init>(RecipeItemHelper.java:121) ~[aef$a.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194118_a(RecipeItemHelper.java:79) ~[aef.class:?]
	at net.minecraft.client.util.RecipeItemHelper.func_194116_a(RecipeItemHelper.java:74) ~[aef.class:?]
	at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(ShapelessRecipes.java:88) ~[akx.class:?]
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213) ~[aku.class:?]
	at mrriegel.playerstorage.gui.ContainerExI.func_75130_a(ContainerExI.java:223) ~[ContainerExI.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at mrriegel.playerstorage.Message2Server.handleMessage(Message2Server.java:58) ~[Message2Server.class:?]
	at mrriegel.playerstorage.gui.GuiExI.func_146284_a(GuiExI.java:307) ~[GuiExI.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443) ~[blk.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323) ~[bmg.class:?]
	at mrriegel.limelib.gui.CommonGuiContainer.func_73864_a(CommonGuiContainer.java:66) ~[CommonGuiContainer.class:?]
	at mrriegel.playerstorage.gui.GuiExI.func_73864_a(GuiExI.java:332) ~[GuiExI.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) ~[blk.class:?]
	at mrriegel.limelib.gui.CommonGuiContainer.func_146274_d(CommonGuiContainer.java:85) ~[CommonGuiContainer.class:?]
	at mrriegel.playerstorage.gui.GuiExI.func_146274_d(GuiExI.java:367) ~[GuiExI.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757) ~[bib.class:?]
	... 17 more

**Comment by SevenChords** [comment]
does the log help in any way?

**Comment by KidsDontPlay** [comment]
probably

**Comment by KidsDontPlay** [comment]
sorry, I have no idea why this crash happens.
does it only happen when you clear the grid? did you have the same problems with other crafting tables (vanilla, AE2, refined storage)?
maybe it's caused by another mod. try only with player storage (and limelib) installed

**Comment by SevenChords** [comment]
Yes, only happens when clearing the grid, tested with vanilla crafting table, didn't happen, ae and refined storage not installed, the only thing it may be an incompability is the detect function from better questing somehow, but no other mod was involved in the items/events handeled while crafting/clearing the grid

**Comment by KidsDontPlay** [comment]
show me your modlist. and forge version

**Comment by SevenChords** [comment]
![bildschirmfoto 2018-03-12 um 22 48 57](https://user-images.githubusercontent.com/31819497/37311506-c1ec25d4-2647-11e8-8d4a-1b1f04dd01cd.png)
![bildschirmfoto 2018-03-12 um 22 49 16](https://user-images.githubusercontent.com/31819497/37311507-c20e355c-2647-11e8-8050-80659195886a.png)
![bildschirmfoto 2018-03-12 um 22 49 50](https://user-images.githubusercontent.com/31819497/37311508-c235a39e-2647-11e8-8474-707dde95e8cb.png)

**Comment by SevenChords** [comment]
java version is 8 update 151

**Comment by KidsDontPlay** [comment]
is that a public modpack? if so, which one?

**Comment by SevenChords** [comment]
it's the "Peace of mind" pack up on curseforge, your mod was a manual addition

**Comment by KidsDontPlay** [comment]
ok, I'm gonna test it with that pack

**Comment by KidsDontPlay** [comment]
WAIT!! why the heck do you use version __1.1.1__ ??
use a recent version!

**Comment by SevenChords** [comment]
oh, that might be it...
i just copied the file from another modpack where it was working fine, will test the bug with the most recent version and give you feedback wheather it is still present

**Comment by SevenChords** [comment]
ok, that was it, sorry to waste your time, but with the 1.2.5 version of the mod everything was fine
