### ISSUE TITLE
[1.12.2] if you open Trashcan crash

### ISSUE THREAD

**Issue by Silverrain2004** [KidsDontPlay/PlayerStorage#46]
Modversion: playerstorage-1.12.2-1.3.9

Forgeversion: forge-1.12.2-14.23.5.2768

I have a strange Error, if i click on Trashcan in Playerstorage, i got kicked with an error. Is it possible to Link
Playerstorage-Trashcan to normal one? or like the FTButilities one? or maybe an option so i can disable it?

**Comment by KidsDontPlay** [comment]
show crashlog?

**Comment by 2781762845** [comment]
I have this Error too.
This is my crashlog.
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 82424
    at mrriegel.playerstorage.gui.GuiExI.actionPerformed(GuiExI.java:377)
    at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443)
    at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:323)
    at mrriegel.limelib.gui.CommonGuiContainer.mouseClicked(CommonGuiContainer.java:66)
    at mrriegel.playerstorage.gui.GuiExI.mouseClicked(GuiExI.java:404)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at mrriegel.limelib.gui.CommonGuiContainer.handleMouseInput(CommonGuiContainer.java:85)
    at mrriegel.playerstorage.gui.GuiExI.handleMouseInput(GuiExI.java:439)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: mrriegel.playerstorage.gui.GuiExI
